// GENERATED BY gg_version WriteVersionFile - DO NOT EDIT.
// Kept in sync by test/dna_tssuite_version.test.ts.

/** The version of the `@tssuite/dna-tssuite` package. */
export const dnaTssuiteVersion = '0.1.2';
